### ISSUE TITLE
TarWriter appears to omit base directory

### ISSUE THREAD

**Issue by helrond** [APTrust/dart#125]
As stated in code comments, TarWriter writes directly to a tarball, rather than writing to a directory that is then tarballed. However, it appears that this produces a non-standard tarball without the base directory as a member. 

The tarball produced this way _does_ extract successfully using the `tar` utility (at least on Mac OS Mojave) but re-tarring the extracted directory produces a different tarball with the base directory as a member:
![Screen Shot 2019-08-09 at 2 15 08 PM](https://user-images.githubusercontent.com/607621/62800133-a367a580-bab0-11e9-8292-a722be2c1cbf.png)

This may be something I'm misunderstanding (I'm not an expert in tarballs).

**Comment by diamondap** [comment]
Thanks for filing this. It looks like the tar writer is not creating any directory entries. I wrote it that way on purpose a long time ago, but I cannot remember why, the original reason for omitting directories may no longer be valid. I'll try to look into this in the next week or so.

**Comment by diamondap** [comment]
Should be fixed in https://github.com/APTrust/dart/compare/03337cbe5f68...f43a35571dd5.

**Comment by helrond** [comment]
I've pulled down these commits and created a local build and can confirm expected behavior on both of the issues above (creating directories and consistent filepath structuring within the payload directory).

**Comment by diamondap** [comment]
This looks good in our tests as well.
