### ISSUE TITLE
Creating BagIt profiles from existing templates

### ISSUE THREAD

**Issue by jamiepb** [APTrust/dart#147]
Hello,

I have a question about creating new BagIt profiles in DART. The State Archives of NC has a custom metadata profile in Bagger, as define on the GitHub page. With DART I found how to create a new profile from the UI, but it sounds like from the [documentation ](https://aptrust.github.io/dart-docs/users/bagit/importing/) it isn't currently possible to import a profile such as the JSON file we created for Bagger. That page mentions using a setup module, but it also looks like setup modules are only supported for APTrust and DPN (https://aptrust.github.io/dart-docs/) unless I'm misunderstanding. Our use case is that state agencies use Bagger to bag records for transfer to the State Archives, so they all need to be able to use our metadata profile without having to set it up individually.

**Comment by diamondap** [comment]
Don't bother with setup modules at this point. I have the underlying code in place to import existing BagIt profiles. I just haven't yet exposed that in the UI yet. I'm plan on doing that in the next week or two. I can let you know when that's done.

**Comment by diamondap** [comment]
@jamiepb Can you send a link to (or the json of) the BagIt profile you want to import? I'd like to use it as a test case when I add this feature.

**Comment by jamiepb** [comment]
https://github.com/LibraryOfCongress/bagger/blob/master/bagger-business/src/main/resources/gov/loc/repository/bagger/profiles/SANC-state-profile.json

**Comment by diamondap** [comment]
Try the import feature in the latest version of DART. This page has links to the Windows, Mac, and Linux builds:

https://aptrust.github.io/dart-docs/users/getting_started/

From the menu, choose Settings > BagIt Profiles. At the top of the profiles list, you'll see a new "Import Profile" button. You can import the SANC state profile from this URL (which returns raw json data):

https://raw.githubusercontent.com/LibraryOfCongress/bagger/master/bagger-business/src/main/resources/gov/loc/repository/bagger/profiles/SANC-state-profile.json

Take a couple of minutes to browse through the profile settings after you do the import. DART profiles do not map exactly to the Library of Congress profiles, so DART adds some default settings during the import process. You may want to alter some of those defaults, such as which manifests are required, etc.

**Comment by diamondap** [comment]
Also, please keep in mind this is still beta software and many use cases outside of the APTrust workflow are not yet fully supported. If DART is not yet serving your particular needs, feel free to open more issues.

**Comment by diamondap** [comment]
For instructions on how to import profiles, see https://aptrust.github.io/dart-docs/users/bagit/importing/
