### ISSUE TITLE
Can't run job if there are no Storage Services

### ISSUE THREAD

**Issue by diamondap** [APTrust/dart#220]
It seems that you can't get past the the 'upload targets' stage of a job if you don't have any storage services in the settings?

**Comment by diamondap** [comment]
I can't reproduce this. I see an upload targets page with no targets listed. I click Next and see the "Review and Run" page. I click Run Job, it runs and says the bag is at output path /Users/apd4n/tmp/dart/testbag1.tar. I check the bag, it's complete and valid.

**Comment by mpburgess** [comment]
When creating a job, I cannot move past the 'Upload targets' screen. When clicking 'Next', without any storage services in settings, nothing happens.

Steps taken:
- Changed bagging directory to another location (eg, D:\_temp)
- Created a BagIt Profile with serialization forbidden, only md5 manifests
- Created new job, added a single small file (186.08KB)
- Selected new BagIt Profile in Packaging step
- Filled out info in Bag Metadata step
- When at Upload Targets step, click Next and nothing happens

I have tested this on two Windows 10 machines with the same result.

![DART-screenshot](https://user-images.githubusercontent.com/27799591/75197098-8dea6c80-57b1-11ea-9753-311bbd270a15.jpg)

**Comment by diamondap** [comment]
Thanks. Can you send me the log file from one of the two machines? Click Help > About on the top menu. That will show you the location of the log file. If you can zip it up and attach it to this bug, that will help me track down the problem.

**Comment by mpburgess** [comment]
Log attached. Tried creating a bag with random files selected from different drives on the machine with the same result.

[dart.log.zip](https://github.com/APTrust/dart/files/4252513/dart.log.zip)
