### ISSUE TITLE
Does BagIt Profile need to be mandatory

### ISSUE THREAD

**Issue by whikloj** [APTrust/dart#221]
We are looking at DART as the basis for a similar tool for moving items from around campus and from external donors to our archives & special collections department. 

Currently we want to use BagIt as the transmission format but we don't have a BagIt Profile we are using.

We might decide on one but if we don't require a profile then DART seems to force you to have one.

Looking at the Bagger code it appears (and I am new to Node) to start with a required BagIt Profile to build the bag, so perhaps this is a non-starter. 

But I thought I would ask if Bagger can generate a BagIt bag that complies with the spec but with no additional profile?

If so, would it be possible to look at adding a `-- No BagIt Profile --` option to the job packaging controller to allow people to choose to not use a Profile?

**Comment by whikloj** [comment]
Almost immediately after posting this I had a discussion in which it sounds like we will have some sort of profile for our purposes. 

So if this could just be a question if there is a reason why the Profile is required? Is this a requirement of the Bagger code or just a requirement of APTrust?

**Comment by helrond** [comment]
AFAIK the [BagIt](https://tools.ietf.org/id/draft-kunze-bagit-16.html) and [BagIt Profile](https://bagit-profiles.github.io/bagit-profiles-specification/) specs are two different things. Presumably the BagIt Profile spec relies on BagIt, but there's no dependency the other way around. 

That said, there are a lot of really good reasons for using BagIt Profiles, and honestly I think it's one of the things that distinguishes DART from other similar application (like [Exactly](https://www.weareavp.com/products/exactly/)) which don't use the BagIt Profile spec.

**Comment by whikloj** [comment]
Sorry, maybe I wasn't clear.

DART requires you to select a BagIt Profile if you choose the BagIt format. 

https://github.com/APTrust/dart/blob/master/ui/controllers/job_packaging_controller.js#L99-L101

But if you want to create a BagIt bag without using a BagIt Profile you (seemingly) are unable.

**Comment by diamondap** [comment]
@whikloj DART does require a BagIt Profile, but I just posted a new release that includes an empty profile. You can select the "Empty Profile" when bagging, and you will not have to fill in any tag values, though you will still have to click through the tag screen.

The empty profile produces a bag with a sha256 manifest and a sha256 tag manifest. It conforms to the BagIt spec. You can download the new version from https://aptrust.github.io/dart-docs/users/getting_started/. Note that we bumped the version number to 2.0.1.

Other release notes for 2.0.1 are in https://github.com/APTrust/dart/blob/master/ReleaseNotes.md

Let me know if this works for you.

**Comment by whikloj** [comment]
Thanks @diamondap, I'll give it a try.

**Comment by diamondap** [comment]
Closing. Work-around is to use empty profile, which is in 2.0.1 and later. Empty profile describes the structure of a valid bag without requiring user-entered tag data.

**Comment by diamondap** [comment]
Closing. Work-around is to use empty profile, which is in 2.0.1 and later. Empty profile describes the structure of a valid bag without requiring user-entered tag data.
