### ISSUE TITLE
Value for tag 'BagIt-Profile-Identifier' in bag-info.txt is missing.

### ISSUE THREAD

**Issue by mpburgess** [APTrust/dart#222]
I receive the error 'Value for tag 'BagIt-Profile-Identifier' in bag-info.txt is missing.' when trying to run a job on a Windows 10 machine:

![image](https://user-images.githubusercontent.com/27799591/75410266-6fca6b00-596f-11ea-8c0c-29ec64f3416a.png)

Log file: [dart.log.zip](https://github.com/APTrust/dart/files/4259382/dart.log.zip)

**Comment by diamondap** [comment]
@mpburgess  I was able to reproduce that. It should be fixed in version 2.0.1. Download links are at https://aptrust.github.io/dart-docs/users/getting_started/. Let me know if this fixes the issue.

**Comment by mpburgess** [comment]
Great - I was able to complete a job successfully after downloading 2.0.1.
