### ISSUE TITLE
Use password input for answers to sensitive config questions

### ISSUE THREAD

**Issue by helrond** [APTrust/dart#275]
As part of its configuration import/export, DART allows the configuration of questions that can be answered by users. These questions are likely to contain sensitive information (login credentials, etc). However, the inputs for the answers to these questions are plain-text. I'd either like the inputs to be password inputs by default, or allow users to specify which questions contain sensitive data that should be masked.

**Comment by diamondap** [comment]
Currently, the only password input in DART is for the password field of a Storage Service. This would be the password someone uses to connect to an SFTP server, or the access key used to connect to an S3 bucket. Are there other fields you can think of that should be masked?

**Comment by helrond** [comment]
I don't currently have a use case for masking other fields, so from my perspective it would be fine if only the password field was masked.

**Comment by diamondap** [comment]
This should be fixed in the latest build, which should be available for download in the next 30 minutes or so.
