### ISSUE TITLE
Unserialized bags which match existing path are invalid

### ISSUE THREAD

**Issue by helrond** [APTrust/dart#280]
When creating an unserialized bag and there is a path in the target directory which matches the bag identifier, I get bag validation errors because more files are found than expected.

<img width="439" alt="Screen Shot 2020-05-22 at 3 32 27 PM" src="https://user-images.githubusercontent.com/607621/82707319-72bcbb00-9c41-11ea-8886-242e237a0415.png">

<img width="1159" alt="Screen Shot 2020-05-22 at 3 28 32 PM" src="https://user-images.githubusercontent.com/607621/82707066-e90ced80-9c40-11ea-969e-3f9c18a6d64f.png">

**Comment by diamondap** [comment]
This should be fixed in v2.0.8. Try downloading the new build. Links are at https://aptrust.github.io/dart-docs/users/getting_started/

**Comment by helrond** [comment]
Great! Confirming this works on Mac. The original error report came from Windows so I'm asking my colleague to confirm on that OS.

**Comment by helrond** [comment]
Confirmed that this works on Windows as well. Thanks for the quick fix!
