### ISSUE TITLE
SFTP test errors on Mac OS Catalina

### ISSUE THREAD

**Issue by diamondap** [APTrust/dart#318]
Thanks, Andrew. I ran the `npm test -- --runInBand` on this version and here's the result: 

 ```
Summary of all failing tests
 FAIL  plugins/network/sftp_client.test.js (7.932 s)
  ● Upload handles Permission denied

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 2

      90 |         expect(result.info).toBeNull();
      91 |         expect(result.warning).toBeNull();
    > 92 |         expect(result.errors.length).toEqual(1);
         |                                      ^
      93 |         expect(result.errors[0]).toMatch(/authentication methods failed/);
      94 |         done();
      95 |     });

      at SFTPClient.<anonymous> (plugins/network/sftp_client.test.js:92:38)
      at Client.<anonymous> (plugins/network/sftp_client.js:120:18)
      at doNextAuth (node_modules/ssh2/lib/client.js:415:12)
      at tryNextAuth (node_modules/ssh2/lib/client.js:484:5)
      at SSH2Stream.onUSERAUTH_FAILURE (node_modules/ssh2/lib/client.js:597:5)
      at parsePacket (node_modules/ssh2-streams/lib/ssh.js:3682:10)
      at SSH2Stream._transform (node_modules/ssh2-streams/lib/ssh.js:701:13)
      at SSH2Stream._read (node_modules/ssh2-streams/lib/ssh.js:253:15)

  ● Upload handles unspecfied failure

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      111 | });
      112 | 
    > 113 | test('Upload handles unspecfied failure', done => {
          | ^
      114 |     var ss = getStorageService();
      115 |     var client = new SFTPClient(ss);
      116 |     client.on('finish', function(result) {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (plugins/network/sftp_client.test.js:113:1)


Test Suites: 1 failed, 86 passed, 87 total
Tests:       2 failed, 571 passed, 573 total
Snapshots:   0 total
Time:        59.603 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

```

_Originally posted by @jwestgard in https://github.com/APTrust/dart/issues/317#issuecomment-666587298_

**Comment by diamondap** [comment]
When running tests, DART starts a minimal, lightweight SFTP server. The code is in https://github.com/APTrust/dart/blob/master/plugins/network/sftp_server2.js. Mac OS should pop up a message asking whether you want to permit the process to accept incoming connections. If you clicked No, or if you didn't answer the prompt, you'll see the errors above.

FYI, if you're not planning on developing for DART, you won't need to download the source or run the test suite.

**Comment by jwestgard** [comment]
Thanks, Andrew.  Mac OS doesn't seem to be popping open the necessary window.

**Comment by jwestgard** [comment]
I have no immediate plans to contribute, other than to provide feedback and testing as a user of DART, so you may want to just close this issue.  I don't really know what's going on, but it seems plausible that Catalina is blocking the popup SFTP server.  This seems more plausible if you've not had occasion to test on the version of Mac OS that I'm running.  If you have then maybe I have some system conflicts specific to my local environment.

**Comment by diamondap** [comment]
I'm curious to see what's causing the failure, and I'm not sure my diagnosis above is correct. I just pushed a change to try to log more info about that test when it fails. If you have a minute, pull the latest code and run the tests again. They'll still fail, but they should print an additional message to console saying what errors actually occurred.

**Comment by jwestgard** [comment]
OK. Here's the console output: https://gist.github.com/jwestgard/8dcf1d9b03daaf00c0856d9476405997

**Comment by diamondap** [comment]
The sftp test server and related tests were deleted in v2.0.17 because the server is incompatible with the newer version of ssh2. The server code was an incomprehensible mess and needs to be rewritten. Once that's done, we need a new set of connection/upload/download tests for the sftp client.

**Comment by diamondap** [comment]
Closing this because we've removed the problematic tests. Rebuilding these tests will be a separate issue for later.
