### ISSUE TITLE
.tar packaging producing no output

### ISSUE THREAD

**Issue by kieranjol** [APTrust/dart#513]
I'm on MacOS 12.3, using GUI Version: DART 2.0.17 with Node.js v12.18.3 for darwin-x64-21.4.0, but have also tested this on Windows 10 as well.

In the Packaging windows, if I select `.tar` instead of `Bagit`, and create a bag in the default local storage, no tar file appears in the destination but a successful job output is reported:
<img width="1097" alt="Screenshot 2022-03-29 at 12 34 10" src="https://user-images.githubusercontent.com/1127102/160628897-41fd4e23-67da-413e-b2ef-32d34733d52d.png">

and the only reference in the log is:
`2022-03-29T11:33:53.391Z - info: Process 2664 exited with code 0, signal null`

Using the Bagit Package Format option with none or .tar serialisation results in successful outputs with bags appearing in the destination folder.

**Comment by diamondap** [comment]
Confirmed locally on DART 2.0.17 with Node.js v12.18.3 for darwin-x64-21.4.0.

No tar file is created, and on top of that, the bag validator tries to validate the empty tar file. It should validate bags only. (If the job has no BagIt profile selected, DART should not even attempt to validate.)

Debug output from local test:

OperationResult {
  operation: 'validation',
  provider: 'DART BagIt validator',
  filepath: '/Users/diamond/.dart/bags/RandomGoSource.tar',
  filesize: 0,
  fileMtime: null,
  remoteChecksum: null,
  attempt: 3,
  started: '2022-03-30T14:46:28.853Z',
  completed: '2022-03-30T14:46:28.855Z',
  remoteURL: null,
  info: null,
  warning: null,
  errors: [
    "Error gathering info about bag: ENOENT: no such file or directory, stat '/Users/diamond/.dart/bags/RandomGoSource.tar'",
    'The bag to be validated does not exist at /Users/diamond/.dart/bags/RandomGoSource.tar'
  ]
}

**Comment by diamondap** [comment]
Forgot to close this. This is fixed (for now) in version 2.0.20, which no longer presents the .tar format as an option. For now, BagIt is the only format option. We never fully implemented the tar format. If/when we do, we'll restore .tar as a format option.
