### ISSUE TITLE
File extension in output path does not update in Packaging window when changing serialisation

### ISSUE THREAD

**Issue by kieranjol** [APTrust/dart#519]
I'm on Version 2.0.19 (2.0.19) on MacOS.
Steps to reproduce:
* In the packaging window, select Bagit as Package format, any profile can be selected
* Do not enter anything for serialization yet
* Enter any text in package name
* Change serialization to .tar, and the file extension will not update.
* When you run this job, you will get None serialization instead of .tar
* You can get the file extension to update if you select the blank/None option for serialization, and then select a .tar serialization again. Changing the package name will cause the file extenstion to update in output path.

Another use case that triggers this is:
* Start a new job and when you get to the Packaging window, select None for Serialization
* Enter a package name
* Now I change my mind, and I want to select .tar instead for serialiation
* When I click next and execute the job, DART has ignored the .tar serialization and has used None instead.

I'm guessing that the fix here would require some sort of refreshing of values when serialization is changed so that the new option is acknowledge but also Output Path is updated?

Best,

Kieran O'Leary
Digital Preservation Manager
National Library of Ireland

**Comment by diamondap** [comment]
Thanks for noting this. It's going to be a while before I can get to this.
