### ISSUE TITLE
Make default bagging directory not hidden?

### ISSUE THREAD

**Issue by kieranjol** [APTrust/dart#520]
Dart's default bagging directory is `$HOME/.dart` . While this is less of an issue on Windows, there can be an issue instructing users on how to actually open this directory on Mac . I've instructed users to immediately click on the output path link in the final Review and Run page after the job has completed, and then copy/paste the package elsewhere if they're not planning on uploading immediately.
Is there a reason why the default dir is a hidden directory, and at the very least, could this be changed? Ideally, a folder could be created on the desktop by default as it would be the most accessible, but it might be annoying?

**Comment by diamondap** [comment]
Yes, the default should probably change. A common problem is that users don't notice the bags that have accumulated in the bagging directory, and then wonder why they have so little disk space after building a few very large bags.

For now, you can change the bagging directory.

1. From DART's top menu, choose **Settings > Application Settings**.
2. Click on **Bagging Directory**.
3. Enter a new directory name in the Value field.
4. Click **Save**.
