### ISSUE TITLE
Windows 10 2.0.21 javascript installation error

### ISSUE THREAD

**Issue by kieranjol** [APTrust/dart#533]
When installing the 2.0.21 version, it fails installation. I've tried three times, uninstalled previous dart, restarted PC, same issue.

![image](https://user-images.githubusercontent.com/1127102/184607038-0c7db86b-c246-4f19-96ab-89b1b8f2de80.png)

**Comment by kieranjol** [comment]
I've just confirmed the issue on another Win10 laptop.

**Comment by diamondap** [comment]
Try the link now. I just rebuilt and re-uploaded the installer. https://s3.amazonaws.com/aptrust.public.download/DART/DART+Setup+2.0.21.exe

**Comment by kieranjol** [comment]
Dart now installs, thank you!
